services:
    mmc_card.Request:
        class: MMC\CardBundle\Services\CardProcessor\Request
    mmc_card.Response:
        class: MMC\CardBundle\Services\CardProcessor\Response
    mmc_card.CardProcessor:
        alias: mmc_card.ChainCardProcessor
    mmc_card.ChainCardProcessor:
            class: MMC\CardBundle\Services\CardProcessor\ChainCardProcessor
    mmc_card.CreateCardProcessor:
        class: MMC\CardBundle\Services\CardProcessor\CreateCardProcessor
        tags:
            - { name: mmc_card.ChainCardProcessor }
    mmc_card.ValidationCardProcessor:
        class: MMC\CardBundle\Services\CardProcessor\ValidationCardProcessor
        tags:
            - { name: mmc_card.ChainCardProcessor }
        arguments:
            - '@mmc_card.card_item_validator'
    mmc_card.EditCardProcessor:
        class: MMC\CardBundle\Services\CardProcessor\EditCardProcessor
        tags:
            - { name: mmc_card.ChainCardProcessor }
    mmc_card.ArchiveSingleCardProcessor:
        class: MMC\CardBundle\Services\CardProcessor\ArchiveSingleCardProcessor
        tags:
            - { name: mmc_card.ChainCardProcessor }
    mmc_card.ArchiveMultipleCardProcessor:
        class: MMC\CardBundle\Services\CardProcessor\ArchiveMultipleCardProcessor
        tags:
            - { name: mmc_card.ChainCardProcessor }
    mmc_card.DeleteSingleDraftCardProcessor:
        class: MMC\CardBundle\Services\CardProcessor\DeleteSingleDraftCardProcessor
        tags:
            - { name: mmc_card.ChainCardProcessor }
    mmc_card.DeleteMultipleDraftCardProcessor:
        class: MMC\CardBundle\Services\CardProcessor\DeleteMultipleDraftCardProcessor
        tags:
            - { name: mmc_card.ChainCardProcessor }

    mmc_card.form.type.status_validation:
        class: MMC\CardBundle\Form\Type\StatusValidationType
        tags:
            - { name: form.type }

    mmc_card.card_item_validator:
        class: MMC\CardBundle\Services\CardItemValidator
        arguments:
            - '@validator'
            - '@translator'

    mmc_card.card_voter:
        class: MMC\CardBundle\Security\Voter\CardVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    mmc_card.twig_extension:
        class: MMC\CardBundle\Twig\MMCCardExtension
        public: false
        arguments: ['@mmc_card.card_item_validator']
        tags:
            - { name: twig.extension }
